name: DPR TEST 10th JAN

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "Seenu24492-patch-1" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Build job
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run build script
        run: echo Hello, world!

  # Test job
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Continue-on-error flag
    continue-on-error: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test scripts
        run: |
          echo Running Unit Tests
          # Replace the below lines with the actual commands to run your tests
          echo "Running test: echo hello world"
          output=$(echo Hello, world!)
          if [ "$output" != "Hello, world!" ]; then 
            echo "Test failed: output wasn't 'Hello, world!'"
            exit 1
          else
            echo "Test passed: output is 'Hello, world!'"
          fi

      - name: Run additional test scripts
        run: |
          echo Add other actions to test
          echo test, and deploy your project.

      - name: Create artifact directory
        run: mkdir -p path/to/artifact

      - name: Write greeting to artifact
        run: echo hello > path/to/artifact/world.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: path/to/artifact/world.txt

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: download_artifact

      - name: Verify artifact contents
        run: |
          if grep -q "hello" download_artifact/world.txt; then
            echo "Test passed: 'hello' found in artifact"
          else
            echo "Test failed: 'hello' not found in artifact"
            exit 1
          fi
